[package]
name = "ctt-curve-bn254-snarks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
constantine-sys = { path = "../constantine-sys" }