# Constantine
# Copyright (c) 2018-2019    Status Research & Development GmbH
# Copyright (c) 2020-Present Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

# Test with:
#   nim c -r -d:release --hints:off --warnings:off --outdir:build/tmp --nimcache:nimcache/tmp tests/commitments/t_kzg_multiproofs.nim

import
  constantine/named/algebras,
  constantine/named/zoo_generators,
  constantine/math/[ec_shortweierstrass, arithmetic, extension_fields],
  constantine/math/elliptic/ec_multi_scalar_mul,
  constantine/math/polynomials/[polynomials, fft_fields, fft_ec],
  constantine/math/matrix/toeplitz,
  constantine/math/pairings/pairings_generic,
  constantine/platforms/[abstractions, allocs, bithacks, views, primitives]


# TODO: consistent indices i, j, k, c, b across all implementation and prover/verifier

# #############################################################
#                                                             #
#           KZG multiproofs for multi-evaluations on a coset  #
#                    Naive implementation                     #
#                                                             #
# #############################################################

func kzg_coset_prove_naive*[N: static int, Name: static Algebra](
       proof: var EC_ShortW_Aff[Fp[Name], G1],
       poly: PolynomialCoef[N, Fr[Name]],
       cosetShift: Fr[Name], L: static int,
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]]) {.tags:[HeapAlloc, Vartime], meter.} =
  ## Compute a KZG multi-evaluation proof for a polynomial
  ##  at L points on a coset.
  ##
  ## This is the NON-OPTIMIZED "schoolbook" O(n²) algorithm using polynomial long division.
  ## For production use with many cells, see `kzg_coset_prove` (FK20 O(n log n)).
  ##
  ## Background on Cosets
  ## ~~~~~~~~~~~~~~~~~~~~
  ##
  ## A coset is a shifted subgroup. In KZG data availability sampling:
  ##   - We have a subgroup G of order L, generated by ω (L-th root of unity)
  ##   - The coset for cell i is: hᵢ * G = {hᵢ, hᵢ·ω, hᵢ·ω², ..., hᵢ·ωᴸ⁻¹}
  ##   - where hᵢ is the coset representative (different for each cell)
  ##
  ## The proof allows verifying all L evaluations simultaneously with a single G1 element.
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## Algorithm
  ## ~~~~~~~~~
  ##
  ## Given polynomial p(X) and coset points {hω⁰, hω¹, ..., hωᴸ⁻¹}:
  ##
  ## 1. Compute evaluations: yⱼ = p(hωʲ) for j in 0..L-1
  ##
  ## 2. Build vanishing polynomial:
  ##      Z(X) = (X - hω⁰)(X - hω¹)...(X - hωᴸ⁻¹)
  ##           = Xᴸ - hᴸ
  ##    In coefficient form: [-hᴸ, 0, 0, ..., 0, 1] (degree L)
  ##
  ## 3. Compute quotient polynomial q(X) = (p(X) - I(X)) / Z(X) via polynomial long division
  ##    Note: using Lagrange interpolation the interpolation polynomial is
  ##
  ##        I(X) = ∑ᵢ₌₀ᵏ⁻¹ yᵢ ∏ⱼ₌₀ᵏ⁻¹ (X-ωʲ)/(ωᶦ-ωʲ) with i≠j
  ##
  ##    and takes the same values as p(X) at the roots.
  ##
  ## 4. Compute proof = [q(τ)]₁ = Σ qᵢ·[τᶦ]₁ via linear combination
  ##
  ## Verification Equation
  ## ~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## The verifier checks:
  ##    e(commitment-I(τ), [1]₂) = e(proof, Z(τ))
  ## with
  ##    commitment =  [p(τ)]₁
  ##    proof = q(τ) = (p(τ)-I(τ))/Z(τ)
  ##
  ## As we open I
  ##
  ## Parameters
  ## ~~~~~~~~~~
  ##
  ## - proof: Output KZG proof (single G1 element)
  ## - poly: Input polynomial in coefficient form (degree N-1)
  ## - h: Coset representative (the "shift" or "offset")
  ## - rootsOfUnity: A set of roots of unity of size 2^K with K > L
  ##                 the L-th roots of unity are a subset `rootsOfUnity[i*K/L]`
  ## - powers_of_tau: SRS [G, τG, τ²G, ..., τᴺ⁻¹G] in affine form
  ##
  ## References
  ## ~~~~~~~~~~
  ##
  ## - https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html#multiproofs
  ## - D23 - Danksharding encoding.md

  static:
    doAssert N > L, "Polynomial degree must be > coset size"
    doAssert L.isPowerOf2_vartime(), "Coset size L must be a power of 2"

  # Build vanishing polynomial -
  #   Z(X)=(X-hω⁰)(X-hω¹)...(X-hωᴸ⁻¹) = Xᴸ - hᴸ
  #   ==> in coefficient form: [-hᴸ, 0, 0, ..., 0, 1] (degree L)
  let hL = cosetShift ~^ uint32(L)
  var divisor {.noInit.}: PolynomialCoef[L + 1, Fr[Name]]
  divisor.coefs[0].neg(hL)
  for i in 1 ..< L:
    divisor.coefs[i].setZero()
  divisor.coefs[L].setOne()

  # Compute quotient polynomial q(X) = (p(X)-I(X)) / Z(X)
  # If we rearrange terms we have:
  #    p(X) = Z(X)·q(X) + I(X)
  # i.e. I(X) is the remainder of the polynomial division
  # of p(X) by Z(X) and q(X) its quotient.
  # With coefficient form polynomial synthetic division
  # we get the quotient directly without needing to subtract I(X)
  # similar to divmod for integers
  var quotient {.noInit.}: PolynomialCoef[N, Fr[Name]]
  polyDiv(quotient, poly, divisor)

  # Compute proof [q(τ)]₁ = Σ qᵢ·[τᶦ]₁
  var proofJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  proofJac.multiScalarMul_vartime(quotient.coefs, powers_of_tau.coefs)
  proof.affine(proofJac)

func kzg_coset_verify*[L: static int, Name: static Algebra](
       domain: FrFFT_Descriptor[Fr[Name]],
       commitment: EC_ShortW_Aff[Fp[Name], G1],
       proof: EC_ShortW_Aff[Fp[Name], G1],
       ys: array[L, Fr[Name]],
       cosetShift: Fr[Name],
       powers_of_tau: openArray[EC_ShortW_Aff[Fp[Name], G1]],
       tau_pow_L_g2: EC_ShortW_Aff[Fp2[Name], G2]): bool {.meter.} = # TODO: for now we assume G2 on Fp2
  ## Verify a KZG commitment to a polynomial p(X)
  ## at L evaluation points forming a coset
  ##
  ## With:
  ##   - commitment C = [p(τ)]₁
  ##   - proof π = [q(τ)]₁ = [(p(τ)-I(τ))/Z(τ)]₁
  ##     with I(X) the Lagrange interpolation polynomial on the evaluation coset.
  ##     and Z(X) the vanishing polynomial on that coset
  ##   - ys: evaluation of p(X) at a coset
  ##         in bit-reversed order
  ##   - h: coset representative (e.g., ωⁱ for i-th cell)
  ##   - powers of tau on G: [1]₂, [τ]₂, [τ²]₂, ..., [τᴸ]₂
  ##   - [τᴸ]₂
  ##
  ## Verification equation:
  ##   e(commitment - [I(τ)]₁, [1]₂) = e(proof, [Z(τ)]₂)

  # TODO: for now we assume G2 on Fp2 but this is not always true
  # for example BW6-761 has G1 and G2 on Fp.

  debug:
    doAssert powers_of_tau.len >= L

  var
    interpoly {.noInit.}: PolynomialCoef[L, Fr[Name]]
    iTau {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    commitMinusI {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    hL_G2 {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    zTau {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    negG2 {.noInit.}: EC_ShortW_Aff[Fp2[Name], G2]

  # Step 1: Interpolate ys at roots of unity using coset IFFT
  #         The shift is needed to unshift from coset points back to coefficients
  let status = domain.coset_ifft_rn(interpoly.coefs, ys, cosetShift)
  if status != FFT_Success:
    return false

  # Step 2: Compute [I(τ)]₁ = Σᵢ Iᵢ·[τⁱ]₁
  iTau.multiScalarMul_vartime(interpoly.coefs.asUnchecked(), powers_of_tau.asUnchecked(), L)

  # Step 3: Compute C - [I(τ)]₁
  commitMinusI.fromAffine(commitment)
  commitMinusI -= iTau

  # Step 4: Compute vanishing poly evaluation at τ, [Z(τ)]₂ = [τᴸ - hᴸ]₂ in G2
  zTau.fromAffine(tau_pow_L_g2)
  let hL {.noInit.} = cosetShift ~^ uint32(L)
  hL_G2.setGenerator()
  hL_G2.scalarMul_vartime(hL)
  zTau -= hL_G2

  # Step 5: Verify pairing e(commit - [I(τ)]₁, [-1]₂).e(proof, [τᴸ - hᴸ]₂) = 1
  negG2.neg(Name.getGenerator("G2"))
  return pairing_check(commitMinusI, negG2, proof, zTau)

# ############################################################
#
#           FK20 - Fast amortized KZG proofs
#
# ############################################################
#
# Algorithm from FK20 paper (Feist, Khovratovich):
#  https://raw.githubusercontent.com/khovratovich/Kate/master/Kate_amortized.pdf
#
# Long eprint:
# https://eprint.iacr.org/2023/033
#
# Computes multiple KZG proofs simultaneously in O(n log n) time
# instead of O(n²) for individual proofs.
#
# Nomenclature
# ~~~~~~~~~~~~
#
# - N: Polynomial size
# - L: coset size
# - CDS (Circulant Domain Size): Extended domain size = 2 * N/L
#
# For EIP-7594 PeerDAS:
#   N = 4096 (FIELD_ELEMENTS_PER_BLOB),
#   L = 64 (FIELD_ELEMENTS_PER_CELL)
#   N/L = CELLS_PER_BLOB, 64 blobs with each 64 cells
#   CDS = 128

func computePolyphaseDecompositionFourierOffset[N, CDS: static int, Name: static Algebra](
       polyphaseSpectrum: var array[CDS, EC_ShortW_Jac[Fp[Name], G1]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       ecfft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]],
       offset: int = 0): FFT_Status {.tags:[Alloca, HeapAlloc, Vartime], meter.} =
  ## Compute FFT of one polyphase component of the SRS (Toeplitz input spectrum).
  ##
  ## DSP Terminology (Crypto ↔ Signal Processing Mapping)
  ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## This function implements polyphase decomposition followed by FFT:
  ##
  ##   Crypto Name          DSP Equivalent              Mathematical Object
  ##   ─────────────────────────────────────────────────────────────────────
  ##   powers_of_tau        Input signal x[n]          [s^n] basis elements
  ##   offset i             Polyphase phase index      decimation by L
  ##   strided extraction   Polyphase component x_i[m] x[m·L + i]
  ##   polyphaseSpectrum    Input spectrum X_i(ω)      FFT of polyphase component
  ##   CDS                  FFT size / block length    circulant embedding size
  ##
  ## Algorithm (FK23 Proposition 4, Step 1 - Polyphase Decomposition)
  ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## This implements Step 1 of Proposition 4's algorithm for multiproofs:
  ##   1. Extract polyphase component: ŝ_i = {[s^{d-L-1-i}], [s^{d-2L-1-i}], ...} (stride L)
  ##   2. Zero-pad to size CDS (circulant embedding for Toeplitz multiplication)
  ##   3. Compute FFT → ŷ_i = DFT(ŝ_i) (frequency-domain representation)
  ##
  ## The complete Proposition 4 algorithm computes v = Σ_{i<L} Toeplitz_i · ŝ_i by:
  ##   - Computing ŷ_i = DFT(ŝ_i) for each phase i (this function, L times)
  ##   - Computing ŵ_i = DFT(ĉ_i) for polynomial coefficient phases
  ##   - Summing Hadamard products: û = Σ_{i<L} ŵ_i ⊙ ŷ_i
  ##   - Inverse FFT: v = iDFT(û)
  ##
  ## The result is one column of the polyphase filter bank (setup spectrum for phase i).
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## Uses stride to handle smaller sizes from a larger descriptor (e.g., 8192 descriptor for 128-size FFT).
  ##
  ## @param polyphaseSpectrum: Output array for FFT of polyphase component (length CDS)
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ...] (affine, length N)
  ## @param ecfft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)
  ## @param offset: Polyphase phase index (default 0, range 0..L-1)
  ##
  ## References:
  ##   - FK23 Paper (Feist-Khovratovich 2023), Proposition 4, Step 1: https://eprint.iacr.org/2023/033
  ##     "The coefficients v can be computed using 2r log 2r scalar multiplications"
  ##   - DSP: Polyphase decomposition + circulant embedding FFT
  ##   - Toeplitz matrix-vector multiplication: http://www.netlib.org/utk/people/JackDongarra/etemplates/node384.html
  ##
  const CDSdiv2 = CDS shr 1
  const L = (2 * N) div CDS
  static: doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"
  doAssert ecfft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  # Extract polyphase component directly into output buffer (convert affine to Jacobian for FFT)
  # This is the polyphase decomposition: x_i[m] = x[m·L + offset] with reversal
  let start = N - L - 1 - offset
  var j = start
  for i in 0 ..< CDSdiv2 - 1:
    polyphaseSpectrum[i].fromAffine(powers_of_tau.coefs[j])
    j -= L
  # Handle last element before zero padding
  if j >= 0:
    polyphaseSpectrum[CDSdiv2 - 1].fromAffine(powers_of_tau.coefs[j])
  else:
    polyphaseSpectrum[CDSdiv2 - 1].setNeutral()
  for j in CDSdiv2 ..< CDS:
    polyphaseSpectrum[j].setNeutral()

  # FFT in-place to get polyphase spectrum (frequency-domain representation)
  result = ec_fft_nn(ecfft_desc, polyphaseSpectrum, polyphaseSpectrum)

func computePolyphaseDecompositionFourier*[N, L, CDS: static int, Name: static Algebra](
       polyphaseSpectrumBank: var array[L, array[CDS, EC_ShortW_Aff[Fp[Name], G1]]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       ecfft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]]) {.tags:[Alloca, HeapAlloc, Vartime], meter.} =
  ## Compute polyphase decomposition Fourier transform for all L phases (complete polyphase filter bank).
  ##
  ## DSP Terminology (Crypto ↔ Signal Processing Mapping)
  ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## This is the complete FK20 preprocessing phase that builds a polyphase filter bank:
  ##
  ##   Crypto Name               DSP Equivalent                    Mathematical Object
  ##   ─────────────────────────────────────────────────────────────────────
  ##   polyphaseSpectrumBank     Polyphase spectrum bank      {X_i(ω)} for i in 0..L-1
  ##   L                         Number of phases             decimation factor
  ##   CDS                       FFT size per phase           circulant embedding size
  ##   powers_of_tau             Input signal (SRS)           x[n] = [s^n]
  ##
  ## Algorithm Overview
  ## ~~~~~~~~~~~~~~~~~~
  ##
  ## For each phase (offset) i in 0..L-1:
  ##   1. Extract polyphase component (stride L, offset i)
  ##   2. Compute FFT → one column of polyphaseSpectrumBank
  ##   3. Batch convert Jacobian to affine (single batch inversion for all L×CDS points)
  ##
  ## The result is a bank of L precomputed spectra used for fast Toeplitz matrix-vector
  ## multiplication. This corresponds to the "analysis filter bank" in multirate DSP.
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## This corresponds to:
  ##   - fk20_multi.py lines 46-49: xext_fft = [] for i in range(l)
  ##   - c-kzg-4844: s->x_ext_fft_columns (precomputed during setup)
  ##
  ## The result can be cached and reused for multiple polynomials.
  ##
  ## @param polyphaseSpectrumBank: Output array[L][CDS] - bank of polyphase spectra (affine form)
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ..., τⁿ⁻¹G] (affine, length N)
  ## @param ecfft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)
  ##
  ## @see computePolyphaseDecompositionFourierOffset for computing a single phase
  ##
  ## References:
  ##   - FK23 Paper (Feist-Khovratovich 2023), Proposition 4: https://eprint.iacr.org/2023/033
  ##   - DSP: Polyphase filter banks, multirate signal processing
  ##   - Toeplitz multiplication: http://www.netlib.org/utk/people/JackDongarra/etemplates/node384.html
  static: doAssert CDS * L == 2 * N
  doAssert ecfft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  # Compute all phases in Jacobian form first
  let polyphaseSpectrumBankJac = allocHeapArrayAligned(array[CDS, EC_ShortW_Jac[Fp[Name], G1]], L, alignment = 64)

  for offset in 0 ..< L:
    let status = computePolyphaseDecompositionFourierOffset(polyphaseSpectrumBankJac[offset], powers_of_tau, ecfft_desc, offset)
    doAssert status == FFT_Success, "Polyphase decomposition FFT failed at offset " & $offset

  # Half the points are points at infinity. A vartime batch inversion
  # saves a lot of compute, 3*L*CDS
  batchAffine_vartime(
    polyphaseSpectrumBank[0].asUnchecked(),
    polyphaseSpectrumBankJac[0].asUnchecked(),
    L * CDS
  )

  freeHeapAligned(polyphaseSpectrumBankJac)

proc kzg_coset_prove*[L, CDS: static int, Name: static Algebra](
       proofs: var array[CDS, EC_ShortW_Aff[Fp[Name], G1]],
       poly: openArray[Fr[Name]],
       fr_fft_desc: FrFFT_Descriptor[Fr[Name]],
       ec_fft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]],
       polyphaseSpectrumBank: array[L, array[CDS, EC_ShortW_Aff[Fp[Name], G1]]]
      ): void {.tags:[Alloca, HeapAlloc, Vartime], meter.} =
  ## Compute KZG multi-proofs for EIP-7594 cell proofs using FK20 algorithm.
  ##
  ## This implements the FK20 amortized KZG proofs from c-kzg-4844.
  ## Uses Toeplitz matrix-vector multiplication with FFT for O(n log n) performance.
  ##
  ## DSP Terminology (Crypto ↔ Signal Processing Mapping)
  ## ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ##
  ##   Crypto Name               DSP Equivalent                    Role
  ##   ─────────────────────────────────────────────────────────────────────
  ##   polyphaseSpectrumBank     Polyphase filter bank          Precomputed input spectra
  ##   poly                      Filter coefficients            Toeplitz kernel f_i
  ##   proofs                    Output evaluations             Convolution result
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096 (polynomial size)
  ##   L = FIELD_ELEMENTS_PER_CELL = 64 (stride/loop count, evaluations per cell)
  ##   CDS = 2 * CELLS_PER_BLOB = 128 (output proof count)
  ##
  ## Uses stride to handle smaller sizes from larger descriptors (e.g., 8192 descriptor for 128-size FFT).
  ##
  ## Algorithm (Phase 1 + Phase 2 from FK20):
  ##   Use ToeplitzAccumulator to accumulate L Hadamard products in Fourier domain
  ##   MSM per output position, then one amortized EC IFFT
  ##   Zero upper half
  ##   FFT → proofs
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## @param polyphaseSpectrumBank: Precomputed polyphase spectra bank (L × CDS, affine form)
  ## @param proofs: Output array for CDS proofs (affine form)
  ## @param poly: Polynomial coefficients to prove (length N = L*CDS/2, coefficient/monomial form)
  ##              Can be a slice of a larger polynomial array.
  ## @param fr_fft_desc: Precomputed Fr FFT descriptor (order >= CDS, uses stride)
  ## @param ec_fft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)
  const CDSdiv2 = CDS shr 1
  const N = L * CDSdiv2
  doAssert poly.len == N

  static:
    doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"
  doAssert fr_fft_desc.order >= CDS, "Fr FFT descriptor order must be >= CDS"
  doAssert ec_fft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  # Use Toeplitz accumulator with MSM for FK20
  var accum: ToeplitzAccumulator[EC_ShortW_Jac[Fp[Name], G1], EC_ShortW_Aff[Fp[Name], G1], Fr[Name]]
  let status = accum.init(fr_fft_desc, ec_fft_desc, CDS, L)
  doAssert status == Toeplitz_Success, "Internal error: Toeplitz accumulator init failed: " & $status

  let circulant = allocHeapArrayAligned(Fr[Name], CDS, alignment = 64)

  for offset in 0 ..< L:
    makeCirculantMatrix(circulant.toOpenArray(CDS), poly, offset, L)

    # Accumulate FFT of circulant coefficients with affine points (already affine from setup)
    # Offset is tracked automatically inside accumulator
    let status = accum.accumulate(
      circulant.toOpenArray(CDS),
      polyphaseSpectrumBank[offset]
    )
    doAssert status == Toeplitz_Success, "Internal error: Toeplitz accumulator failed at offset " & $offset & ": " & $status

  freeHeapAligned(circulant)

  # MSM per position + one amortized IFFT at the end
  let u = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)
  let status2 = accum.finish(u.toOpenArray(CDS))
  doAssert status2 == Toeplitz_Success, "Internal error: Toeplitz accumulator finish failed: " & $status2

  # Zero upper half, degree is CDS/2 - 1
  for i in CDSdiv2 ..< CDS:
    u[i].setNeutral()

  # FFT in-place to get proofs — reuse u buffer
  let status3 = ec_fft_desc.ec_fft_nn(u.toOpenArray(CDS), u.toOpenArray(CDS))
  doAssert status3 == FFT_Success, "Internal error: EC FFT failed: " & $status3

  proofs.asUnchecked().batchAffine_vartime(u, proofs.len)
  freeHeapAligned(u)

# ############################################################
#
#  Multi-multi-proof batch verification for coset multiproofs
#
# ############################################################
#
# Universal verification equation from KDF22 (Kadianakis, Dietrichs, Feist):
# https://ethresear.ch/t/a-universal-verification-equation-for-data-availability-sampling/13240
#
#     e(∑ₖrᵏ·πₖ, [τᴸ]₂) = e(∑ᵢ(∑ₖ∈rowᵢ rᵏ)·Cᵢ - [∑ₖrᵏIₖ(τ)]₁ + ∑ₖrᵏhₖᴸ·πₖ, [1]₂)
#
# with
#   k iterating over the samples being verified
#   i iterating over rows of size the number of blobs B
#   r a random number not under the control of a potentially malicious prover
#     see https://cr.yp.to/badbatch/badbatch-20120919.pdf (Section 3.2)
#     on the use of randomizers to prevent rogue key attacks.
#     and analogue in BLS aggregate signatures: https://ethresear.ch/t/fast-verification-of-multiple-bls-signatures/5407/14
#
# Note: the Ethereum polynomial sampling spec notation
#
#   e(∑ₖrᵏ·πₖ, [τᴸ]₂) = e(∑ᵢ(∑ₖ∈rowᵢ rᵏ)·Cᵢ - [∑ₖrᵏIₖ(τ)]₁ + ∑ₖrᵏhₖᴸ·πₖ, [1]₂)
#           e(LL, LR) = e(RLC - RLI + RLP, [1]₂)
# seems to refer to Left-Left, Left-Right, Right-Left-Commitments/Interpolations/Proofs
#
# PeerDAS Layout: https://notes.ethereum.org/@dankrad/danksharding_encoding
#
# Protocol-wise PeerDAS is using 2D KZG with a matrix organization
#
#           S₀ͺ₀   S₁ͺ₀   S₂ͺ₀    …  S꜀ͺ₀   …  Sₙ/ℓ₋₁ͺ₀
#           S₀ͺ₁   S₁ͺ₁   S₂ͺ₁    …  S꜀ͺ₁   …  Sₙ/ℓ₋₁ͺ₁
#           S₀ͺ₂   S₁ͺ₂   S₂ͺ₂    …  S꜀ͺ₂   …  Sₙ/ℓ₋₁ͺ₂
#             ⋮      ⋮      ⋮     ⋱    ⋮    ⋱    ⋮
#           S₀ͺᵢ   S₁ͺᵢ   S₂ͺᵢ    ⋱  S꜀ͺᵢ   ⋱  Sₙ/ℓ₋₁ͺͺᵢ
#             ⋮      ⋮      ⋮     ⋱    ⋮    ⋱    ⋮
#           S₀ͺ𞁓₋₁ S₁ͺ𞁓₋₁ S₂ͺ𞁓₋₁  …  S꜀ͺ𞁓₋₁ …  Sₙ/ℓ₋₁ͺ𞁓₋₁
#
# Each row represents a polynomial being committed to
# Each sample/cell Sₖͺᵢ corresponds to L evaluations of that polynomial over a coset.
# i.e. each sample commits to a subset of the full row polynomial.

func computeAggRandScaledInterpoly[Name: static Algebra, L: static int](
      interpoly: var PolynomialCoef[L, Fr[Name]],
      evals: openArray[array[L, Fr[Name]]],
      evalsCols: openArray[int],
      domain: FrFFT_Descriptor[Fr[Name]],
      linearIndepRandNumbers: openArray[Fr[Name]],
      N: static int) {.meter.} =
  ## Compute ∑ₖrᵏIₖ(X)
  ##
  ## Input is a "sparse bunch of evals" and their corresponding column.
  ## The row (blob) ID they come from is unnecessary as we commit
  ## to a polynomial (i.e. evaluations and evaluation domain, so the coset)
  ## and not metadata.
  ##
  ## The per-coset evaluations are expected in bit-reversed order
  ##
  ## N is the number of field elements per column
  static:
    doAssert N.isPowerOf2_vartime()
    doAssert L.isPowerOf2_vartime()

  debug:
    doAssert evals.len == evalsCols.len
    doAssert linearIndepRandNumbers.len >= evalsCols.len

  # Runtime validation: prevent out-of-bounds indexing of agg_cols heap allocation
  doAssert evals.len == evalsCols.len, "Internal error: evals and evalsCols must have same length"
  doAssert linearIndepRandNumbers.len >= evalsCols.len, "Internal error: linearIndepRandNumbers must cover all evals"

  const NumCols = N div L
  for k in 0 ..< evalsCols.len:
    let c = evalsCols[k]
    doAssert c >= 0 and c < NumCols, "Internal error: Column index out of bounds: " & $c

  const logNumCols = log2_vartime(uint32(NumCols))

  # 1. Aggregate polynomials evaluated on the same coset (columns)
  #    in Lagrange basis to bound the number of iFFT by N/L
  # We scale each column by a random number not in control of a potentially malicious prover.
  # The numbers themselves don't matter as long as they are linearly independent.
  # and the scaling is consistently applied in all subfunctions of the verification routine.
  # Using the powers of a source `r` crypto secure random number is a convenient solution.

  # agg_cols and agg_cols_used are already zeroed / initialized to false
  # We assume the neutral element is zero (additive notation) so we use raw zeroMem.
  let agg_cols = alloc0HeapArrayAligned(array[L, Fr[Name]], NumCols, alignment = 64)
  let agg_cols_used = alloc0HeapArrayAligned(bool, NumCols, alignment = 64)

  for k in 0 ..< evalsCols.len:
    let col = evalsCols[k]
    for j in 0 ..< L:
      var scaled {.noInit.}: Fr[Name]
      scaled.prod(linearIndepRandNumbers[k], evals[k][j])
      agg_cols[col][j] += scaled
      agg_cols_used[col] = true

  # 2. Each column is evaluated on a different coset so we can't add evaluations,
  #    we move to coefficient form
  zeroMem(interpoly.addr, sizeof(interpoly))

  for c in 0 ..< NumCols:
    if not agg_cols_used[c]:
      continue

    # Compute the per-column interpolation polynomial (IFFT in-place)
    let domainPos = reverseBits(uint32(c), logNumCols)
    let hk = domain.rootsOfUnity[domainPos]

    # agg_cols[c] is in bit-reversed order
    let status = domain.coset_ifft_rn(agg_cols[c], agg_cols[c], hk)
    doAssert status == FFT_Success, "Internal error: coset_ifft_rn failed: " & $status

    # Accumulate directly from agg_cols[c] (now in coefficient form)
    for i in 0 ..< L:
      interpoly.coefs[i] += agg_cols[c][i]

  freeHeapAligned(agg_cols_used)
  freeHeapAligned(agg_cols)

func kzg_coset_verify_batch*[L: static int, Name: static Algebra](
      uniqueCommitments: openArray[EC_ShortW_Aff[Fp[Name], G1]],
      commitmentIdx: openArray[int],
      proofs: openArray[EC_ShortW_Aff[Fp[Name], G1]],
      evals: openArray[array[L, Fr[Name]]],
      evalsCols: openArray[int],
      domain: FrFFT_Descriptor[Fr[Name]],
      linearIndepRandNumbers: openArray[Fr[Name]],
      powers_of_tau: openArray[EC_ShortW_Aff[Fp[Name], G1]],
      tau_pow_L_g2: EC_ShortW_Aff[Fp2[Name], G2], # TODO: for now we assume G2 on Fp2
      N: static int
    ): bool {.meter.} =
  ## Verify multiple KZG multiproofs
  ## organized in a 2D matrix of (commitments, (proof, evaluations)).
  ##
  ## S₀ͺ₀   S₁ͺ₀   S₂ͺ₀    …  S꜀ͺ₀   …  Sₙ/ℓ₋₁ͺ₀
  ## S₀ͺ₁   S₁ͺ₁   S₂ͺ₁    …  S꜀ͺ₁   …  Sₙ/ℓ₋₁ͺ₁
  ## S₀ͺ₂   S₁ͺ₂   S₂ͺ₂    …  S꜀ͺ₂   …  Sₙ/ℓ₋₁ͺ₂
  ##   ⋮      ⋮      ⋮     ⋱    ⋮    ⋱    ⋮
  ## S₀ͺᵢ   S₁ͺᵢ   S₂ͺᵢ    ⋱  S꜀ͺᵢ   ⋱  Sₙ/ℓ₋₁ͺͺᵢ
  ##   ⋮      ⋮      ⋮     ⋱    ⋮    ⋱    ⋮
  ## S₀ͺ𞁓₋₁ S₁ͺ𞁓₋₁ S₂ͺ𞁓₋₁  …  S꜀ͺ𞁓₋₁ …  Sₙ/ℓ₋₁ͺ𞁓₋₁
  ##
  ## Each sample/cell S꜀ͺᵢ corresponds to L evaluations of a polynomial over a coset.
  ## Each row represents a polynomial being committed to.
  ## A commitment is row-wide, every sample within a row maps to the same.
  ##
  ## We use a custom sparse representation of the matrix:
  ## - It is compressed over the rows (commitments), iteration variable i
  ## - We verify some columns of it, iteration variable c
  ##
  ## We verify K samples, iteration variable k.
  ## - A sampleₖ has the following metadata and data:
  ##   - `commitmentIdx` to map to the actual commitment
  ##   - proof πₖ
  ##   - L evaluations in bit-reversed order
  ##   - `evalsCol`ₖ to map to the coset / evaluation domain
  ##
  ## For batch proving we need to prevent rogue key / batch forgeries attacks
  ## when accumulating values with an additively homomorphic scheme like KZG
  ## Hence we scale commitments and evals by a function f(linearIndepRandNumbers, row, col)
  ## with linearIndepRandNumbers not in control of a potentially malicious prover.
  ##
  ## The single KZG multiproof verification equation
  ## verifies the relationship between (commitment, proof, evals)
  ## with `evals` made at a secret τ in the KZG trusted setup.
  ##
  ##    e(commitment - [I(τ)]₁, [1]₂) = e(proof, [Z(τ)]₂)
  ##         e(C - [I(τ)]₁, [1]₂) = e(π, [τᴸ-hᴸ]₂)
  ##
  ## with commitment C = [p(τ)]₁
  ##      proof π = [q(τ)]₁ = [(p(τ)-I(τ))/Z(τ)]₁
  ##        with I(X) the Lagrange interpolation polynomial on the evaluation coset.
  ##        and Z(X) the vanishing polynomial on that coset
  ##      Z(X) = Xᴸ - hᴸ
  ##        with h the coset representative
  ##
  ## Now for 2D multi KZG multiproof verification with random rescaling, the equation is
  ##
  ##   e(∑ₖrᵏ·πₖ, [τᴸ]₂) = e(∑ᵢ(∑ₖ∈rowᵢ rᵏ)·Cᵢ - [∑ₖrᵏIₖ(τ)]₁ + ∑ₖrᵏhₖᴸ·πₖ, [1]₂)
  ##
  ## with k iterating over our potentially sparse (commitment, proof, evals) input samples.
  ## and  i iterating over rows/blobs

  debug:
    doAssert powers_of_tau.len >= L
    doAssert commitmentIdx.len == proofs.len
    doAssert evals.len == proofs.len
    doAssert evalsCols.len == proofs.len
    doAssert linearIndepRandNumbers.len >= proofs.len

  # Runtime validation: prevent out-of-bounds indexing of heap allocations
  if commitmentIdx.len != proofs.len or
     evals.len != proofs.len or
     evalsCols.len != proofs.len or
     linearIndepRandNumbers.len < proofs.len:
    return false

  let numCols = N div L
  for k in 0 ..< proofs.len:
    let i = commitmentIdx[k]
    let c = evalsCols[k]
    if i < 0 or i >= uniqueCommitments.len or c < 0 or c >= numCols:
      return false

  let K = proofs.len

  var
    interpoly {.noInit.}: PolynomialCoef[L, Fr[Name]]
    negG2 {.noInit.}: EC_ShortW_Aff[Fp2[Name], G2]

    ll {.noInit.}, rl {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    rli {.noInit.}, rlp {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]

  # Step 1: Aggregate commitments with random scaling
  #            ∑ᵢ(∑ₖ∈rowᵢ rᵏ)·Cᵢ
  # Concretely, each sampleₖ is scaled by a random factor rᵏ
  # Given that multiple samples may commit to the same polynomial
  # a Cᵢ will be scaled by rᵢ = ∑ₖ∈rowᵢ rᵏ
  # for example if sample k and k+1 commit to the same polynomial
  # rᵢ = rᵏ + rᵏ⁺¹
  # it's significantly cheaper to precompute rᵢ contributions
  # and then the linear combination ∑ᵢrᵢ·Cᵢ
  # than just adding rᵏ·Cᵢ + rᵏ⁺¹·Cᵢ naively as:
  # - Elliptic curve addition is about 15x slower than Field addition
  # - EC scalar mul us about 4375x slower than Field multiplication
  # - We can use multi-scalar multiplication which is sublinear O(n/log n)
  #   with the input size.
  let ri = alloc0HeapArrayAligned(Fr[Name], uniqueCommitments.len, alignment = 64)
  for k in 0 ..< K:
    let i = commitmentIdx[k]
    ri[i] += linearIndepRandNumbers[k]
  rl.multiScalarMul_vartime(ri, uniqueCommitments.asUnchecked(), uniqueCommitments.len)
  ri.freeHeapAligned()

  # Step 2: Compute an aggregate randomly scaled interpolation polynomial
  #                  ∑ₖrᵏIₖ(X)
  #         and evaluate it at trusted setup secret τ
  #                 [∑ₖrᵏIₖ(τ)]₁
  interpoly.computeAggRandScaledInterpoly(
    evals,
    evalsCols,
    domain,
    linearIndepRandNumbers,
    N
  )
  rli.multiScalarMul_vartime(interpoly.coefs.asUnchecked(), powers_of_tau.asUnchecked(), L)
  rl -= rli

  # Step 3: Aggregate ∑ₖrᵏhₖᴸ·πₖ
  let rhl = alloc0HeapArrayAligned(Fr[Name], K, alignment = 64)
  const logCellsPerBlob = log2_vartime(uint32(N div L))
  for k in 0 ..< K:
    let c = uint32 evalsCols[k]
    let hPos = reverseBits(c, logCellsPerBlob)
    let idx = (uint64(hPos) * uint64(L)) mod uint64(domain.order)
    let hL = domain.rootsOfUnity[idx]
    rhl[k].prod(linearIndepRandNumbers[k], hL)
  rlp.multiScalarMul_vartime(rhl, proofs.asUnchecked(), K)
  rhl.freeHeapAligned()

  rl += rlp

  # Step 4: Aggregate ∑ₖrᵏ·πₖ
  ll.multiScalarMul_vartime(linearIndepRandNumbers, proofs)

  # Step 5: Verification
  # e(∑ₖrᵏ·πₖ, [τᴸ]₂).e(∑ᵢ(∑ₖ∈rowᵢ rᵏ)·Cᵢ - [∑ₖrᵏIₖ(τ)]₁ + ∑ₖrᵏhₖᴸ·πₖ, [-1]₂) == 1
  negG2.neg(Name.getGenerator("G2"))
  return pairing_check(ll, tau_pow_L_g2, rl, negG2)
