# Constantine
# Copyright (c) 2018-2019    Status Research & Development GmbH
# Copyright (c) 2020-Present Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

# Test with:
#   nim c -r -d:release --hints:off --warnings:off --outdir:build/tmp --nimcache:nimcache/tmp tests/commitments/t_kzg_multiproofs.nim

import
  constantine/named/algebras,
  constantine/named/zoo_generators,
  constantine/math/[ec_shortweierstrass, arithmetic, extension_fields],
  constantine/math/elliptic/ec_multi_scalar_mul,
  constantine/math/polynomials/[polynomials, fft],
  constantine/math/matrix/toeplitz,
  constantine/math/pairings/pairings_generic,
  constantine/math/io/io_bigints,
  constantine/platforms/[abstractions, allocs, bithacks, views, primitives],
  constantine/serialization/[codecs, codecs_bls12_381]

# #############################################################
#                                                             #
#           KZG multiproofs for multi-evaluations on a coset  #
#                    Naive implementation                     #
#                                                             #
# #############################################################

func kzg_coset_prove_naive*[N: static int, Name: static Algebra](
       proof: var EC_ShortW_Aff[Fp[Name], G1],
       poly: PolynomialCoef[N, Fr[Name]],
       cosetShift: Fr[Name], L: static int,
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute a KZG multi-evaluation proof for a polynomial
  ##  at L points on a coset.
  ##
  ## This is the NON-OPTIMIZED "schoolbook" O(n²) algorithm using polynomial long division.
  ## For production use with many cells, see `kzg_coset_prove` (FK20 O(n log n)).
  ##
  ## Background on Cosets
  ## ~~~~~~~~~~~~~~~~~~~~
  ##
  ## A coset is a shifted subgroup. In KZG data availability sampling:
  ##   - We have a subgroup G of order L, generated by ω (L-th root of unity)
  ##   - The coset for cell i is: hᵢ * G = {hᵢ, hᵢ·ω, hᵢ·ω², ..., hᵢ·ωᴸ⁻¹}
  ##   - where hᵢ is the coset representative (different for each cell)
  ##
  ## The proof allows verifying all L evaluations simultaneously with a single G1 element.
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## Algorithm
  ## ~~~~~~~~~
  ##
  ## Given polynomial p(X) and coset points {hω⁰, hω¹, ..., hωᴸ⁻¹}:
  ##
  ## 1. Compute evaluations: yⱼ = p(hωʲ) for j in 0..L-1
  ##
  ## 2. Build vanishing polynomial:
  ##      Z(X) = (X - hω⁰)(X - hω¹)...(X - hωᴸ⁻¹)
  ##           = Xᴸ - hᴸ
  ##    In coefficient form: [-hᴸ, 0, 0, ..., 0, 1] (degree L)
  ##
  ## 3. Compute quotient polynomial q(X) = (p(X) - I(X)) / Z(X) via polynomial long division
  ##    Note: using Lagrange interpolation the interpolation polynomial is
  ##
  ##        I(X) = ∑ᵢ₌₀ᵏ⁻¹ yᵢ ∏ⱼ₌₀ᵏ⁻¹ (X-ωʲ)/(ωᶦ-ωʲ) with i≠j
  ##
  ##    and takes the same values as p(X) at the roots.
  ##
  ## 4. Compute proof = [q(τ)]₁ = Σ qᵢ·[τᶦ]₁ via linear combination
  ##
  ## Verification Equation
  ## ~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## The verifier checks:
  ##    e(commitment-I(τ), [1]₂) = e(proof, Z(τ))
  ## with
  ##    commitment =  [p(τ)]₁
  ##    proof = q(τ) = (p(τ)-I(τ))/Z(τ)
  ##
  ## As we open I
  ##
  ## Parameters
  ## ~~~~~~~~~~
  ##
  ## - proof: Output KZG proof (single G1 element)
  ## - poly: Input polynomial in coefficient form (degree N-1)
  ## - h: Coset representative (the "shift" or "offset")
  ## - rootsOfUnity: A set of roots of unity of size 2^K with K > L
  ##                 the L-th roots of unity are a subset `rootsOfUnity[i*K/L]`
  ## - powers_of_tau: SRS [G, τG, τ²G, ..., τᴺ⁻¹G] in affine form
  ##
  ## References
  ## ~~~~~~~~~~
  ##
  ## - https://dankradfeist.de/ethereum/2020/06/16/kate-polynomial-commitments.html#multiproofs
  ## - D23 - Danksharding encoding.md

  static:
    doAssert N > L, "Polynomial degree must be > coset size"
    doAssert L.isPowerOf2_vartime(), "Coset size L must be a power of 2"

  # Build vanishing polynomial -
  #   Z(X)=(X-hω⁰)(X-hω¹)...(X-hωᴸ⁻¹) = Xᴸ - hᴸ
  #   ==> in coefficient form: [-hᴸ, 0, 0, ..., 0, 1] (degree L)
  let hL = cosetShift ~^ uint32(L)
  var divisor {.noInit.}: PolynomialCoef[L + 1, Fr[Name]]
  divisor.coefs[0].neg(hL)
  for i in 1 ..< L:
    divisor.coefs[i].setZero()
  divisor.coefs[L].setOne()

  # Compute quotient polynomial q(X) = (p(X)-I(X)) / Z(X)
  # If we rearrange terms we have:
  #    p(X) = Z(X)·q(X) + I(X)
  # i.e. I(X) is the remainder of the polynomial division
  # of p(X) by Z(X) and q(X) its quotient.
  # With coefficient form polynomial synthetic division
  # we get the quotient directly without needing to subtract I(X)
  # similar to divmod for integers
  var quotient {.noInit.}: PolynomialCoef[N, Fr[Name]]
  polyDiv(quotient, poly, divisor)

  # Compute proof [q(τ)]₁ = Σ qᵢ·[τᶦ]₁
  var proofJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  proofJac.multiScalarMul_vartime(quotient.coefs, powers_of_tau.coefs)
  proof.affine(proofJac)

func kzg_coset_verify*[L: static int, Name: static Algebra](
       domain: FrFFT_Descriptor[Fr[Name]],
       commitment: EC_ShortW_Aff[Fp[Name], G1],
       proof: EC_ShortW_Aff[Fp[Name], G1],
       ys: array[L, Fr[Name]],
       cosetShift: Fr[Name],
       powers_of_tau: openArray[EC_ShortW_Aff[Fp[Name], G1]],
       tau_pow_L_g2: EC_ShortW_Aff[Fp2[Name], G2]): bool = # TODO: for now we assume G2 on Fp2
  ## Verify a KZG commitment to a polynomial p(X)
  ## at L evaluation points forming a coset
  ##
  ## Given:
  ##   - commitment C = [p(τ)]₁
  ##   - proof π = [q(τ)]₁ = [(p(τ)-I(τ))/Z(τ)]₁
  ##     with I(X) the Lagrange interpolation polynomial on the evaluation coset.
  ##     and Z(X) the vanishing polynomial on that coset
  ##   - ys: evaluation of p(X) at a coset
  ##         in natural order [p(h·ω⁰), p(h·ω¹), ..., p(h·ωᴸ⁻¹)]
  ##   - h: coset representative (e.g., ωⁱ for i-th cell)
  ##   - powers of tau on G: [1]₂, [τ]₂, [τ²]₂, ..., [τᴸ]₂
  ##   - [τᴸ]₂
  ##
  ## Verify that C is a commitment to p(X)
  ##
  ## Verification equation:
  ##   e(commitment - [I(τ)]₁, [1]₂) = e(proof, [Z(τ)]₂)

  # TODO: for now we assume G2 on Fp2 but this is not always true
  # for example BW6-761 has G1 and G2 on Fp.

  debug:
    doAssert powers_of_tau.len >= L

  var
    interpoly {.noInit.}: PolynomialCoef[L, Fr[Name]]
    iTau {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    commitMinusI {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    hL_G2 {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    zTau {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    negG2 {.noInit.}: EC_ShortW_Aff[Fp2[Name], G2]

  # Step 1: Interpolate ys at roots of unity using coset IFFT
  #         The shift is needed to unshift from coset points back to coefficients
  let status = domain.coset_ifft_rn(interpoly.coefs, ys, cosetShift)
  if status != FFT_Success:
    return false

  # Step 2: Compute [I(τ)]₁ = Σᵢ Iᵢ·[τⁱ]₁
  iTau.multiScalarMul_vartime(interpoly.coefs.asUnchecked(), powers_of_tau.asUnchecked(), L)

  # Step 3: Compute C - [I(τ)]₁
  commitMinusI.fromAffine(commitment)
  commitMinusI -= iTau

  # Step 4: Compute vanishing poly evaluation at τ, [Z(τ)]₂ = [τᴸ - hᴸ]₂ in G2
  zTau.fromAffine(tau_pow_L_g2)
  let hL {.noInit.} = cosetShift ~^ uint32(L)
  hL_G2.setGenerator()
  hL_G2.scalarMul_vartime(hL)
  zTau -= hL_G2

  # Step 5: Verify pairing e(commit - [I(τ)]₁, [-1]₂).e(proof, [τᴸ - hᴸ]₂) = 1
  negG2.neg(Name.getGenerator("G2"))
  return pairing_check(commitMinusI, negG2, proof, zTau)

# ############################################################
#
#           FK20 - Fast amortized KZG proofs
#
# ############################################################
#
# Algorithm from FK20 paper (Feist, Khovratovich):
#  https://raw.githubusercontent.com/khovratovich/Kate/master/Kate_amortized.pdf
#
# Long eprint:
# https://eprint.iacr.org/2023/033
#
# Computes multiple KZG proofs simultaneously in O(n log n) time
# instead of O(n²) for individual proofs.
#
# Nomenclature
# ~~~~~~~~~~~~
#
# - N: Polynomial size
# - L: coset size
# - CDS (Circulant Domain Size): Extended domain size = 2 * N/L
#
# For EIP-7594 PeerDAS:
#   N = 4096 (FIELD_ELEMENTS_PER_BLOB),
#   L = 64 (FIELD_ELEMENTS_PER_CELL)
#   N/L = CELLS_PER_BLOB, 64 blobs with each 64 cells
#   CDS = 128

func getTauExtFft[N, CDS: static int, Name: static Algebra](
       tauExtFft: var array[CDS, EC_ShortW_Jac[Fp[Name], G1]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       ecfft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]],
       offset: int = 0) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Convert powers_of_tau (SRS coefficients) to tauExtFft (FFT of kernel sequence).
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## Uses stride to handle smaller sizes from a larger descriptor (e.g., 8192 descriptor for 128-size FFT).
  ##
  ## @param tauExtFft: Output array for FFT of kernel sequence (length CDS)
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ...] (affine, length N)
  ## @param ecfft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)
  ## @param offset: Offset for kernel extraction (default 0, range 0..L-1)

  const CDSdiv2 = CDS shr 1
  const L = N div CDSdiv2

  static:
    doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"
  doAssert ecfft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  let kernelSeq = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)

  # Extract kernel with stride L and given offset (convert affine to projective for FFT)
  let start = if N >= L + 1 + offset: N - L - 1 - offset else: 0
  var j = start
  for i in 0 ..< CDSdiv2 - 1:
    kernelSeq[i].fromAffine(powers_of_tau.coefs[j])
    j -= L
  kernelSeq[CDSdiv2 - 1].setNeutral()
  for j in CDSdiv2 ..< CDS:
    kernelSeq[j].setNeutral()

  # FFT the kernel to get tauExtFft
  let status = ec_fft_nr(ecFftDesc, tauExtFft, kernelSeq.toOpenArray(CDS))
  if status != FFT_Success:
    freeHeapAligned(kernelSeq)
    return

  freeHeapAligned(kernelSeq)

func getTauExtFftArray*[N, L, CDS: static int, Name: static Algebra](
       tauExtFftArray: var array[L, array[CDS, EC_ShortW_Jac[Fp[Name], G1]]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       ecfft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute tauExtFft for all L offsets.
  ##
  ## This is the complete FK20 preprocessing phase. It computes the FFT of
  ## the kernel sequence for each offset in 0..L-1.
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## This corresponds to:
  ##   - fk20_multi.py lines 46-49: xext_fft = [] for i in range(l)
  ##   - c-kzg-4844: s->x_ext_fft_columns (precomputed during setup)
  ##
  ## The result can be cached and reused for multiple polynomials.
  ##
  ## @param tauExtFftArray: Output array[L][CDS] for FFT of kernel sequences
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ..., τⁿ⁻¹G] (affine, length N)
  ## @param ecfft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)
  ##
  ## @see getTauExtFft for computing a single offset
  static: doAssert CDS * L == 2 * N
  doAssert ecfft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  for offset in 0 ..< L:
    getTauExtFft(tauExtFftArray[offset], powers_of_tau, ecfft_desc, offset)

func kzg_coset_prove*[N, L, CDS: static int, Name: static Algebra](
       tauExtFftArray: array[L, array[CDS, EC_ShortW_Jac[Fp[Name], G1]]],
       proofs: var array[CDS, EC_ShortW_Aff[Fp[Name], G1]],
       poly: PolynomialCoef[N, Fr[Name]],
       fr_fft_desc: FrFFT_Descriptor[Fr[Name]],
       ec_fft_desc: ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute KZG multi-proofs for EIP-7594 cell proofs using FK20 algorithm.
  ##
  ## This implements the FK20 amortized KZG proofs from c-kzg-4844.
  ## Uses Toeplitz matrix-vector multiplication with FFT for O(n log n) performance.
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096 (polynomial size)
  ##   L = FIELD_ELEMENTS_PER_CELL = 64 (stride/loop count, evaluations per cell)
  ##   CDS = 2 * CELLS_PER_BLOB = 128 (output proof count)
  ##
  ## Uses stride to handle smaller sizes from larger descriptors (e.g., 8192 descriptor for 128-size FFT).
  ##
  ## Algorithm (Phase 1 + Phase 2 from FK20):
  ##   For each stride offset in [0, L):
  ##     1. Extract toeplitz coefficients from poly
  ##     2. toeplitzMatVecMul: FFT coeffs + FFT kernel + pointwise multiply + IFFT
  ##     3. Accumulate result
  ##   Zero upper half
  ##   FFT → proofs
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## @param tauExtFft: Precomputed FFT of kernel sequence (length CDS)
  ## @param proofs: Output array for CDS proofs (affine form)
  ## @param poly: Polynomial to prove (length N, coefficient/monomial form)
  ## @param fr_fft_desc: Precomputed Fr FFT descriptor (order >= CDS, uses stride)
  ## @param ec_fft_desc: Precomputed EC FFT descriptor (order >= CDS, uses stride)

  const CDSdiv2 = CDS shr 1
  const N = L * CDSdiv2

  static:
    doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"
  doAssert fr_fft_desc.order >= CDS, "Fr FFT descriptor order must be >= CDS"
  doAssert ec_fft_desc.order >= CDS, "EC FFT descriptor order must be >= CDS"

  let u = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)
  for i in 0 ..< CDS:
    u[i].setNeutral()

  let circulant = allocHeapArrayAligned(Fr[Name], CDS, alignment = 64)

  for offset in 0 ..< L:
    makeCirculantMatrix(circulant.toOpenArray(CDS), poly.coefs, offset, L)

    # Use toeplitzMatVecMulPreFFT with accumulate=true
    # This does: FFT(toeplitzCoeffs) ⊙ kernelFft, then IFFT → result
    # Results are accumulated in time domain
    let status = toeplitzMatVecMulPreFFT(
      u.toOpenArray(CDS),
      circulant.toOpenArray(CDS),
      tauExtFftArray[offset],
      fr_fft_desc,
      ec_fft_desc,
      accumulate = (offset > 0)
    )
    if status != FFT_Success:
      freeHeapAligned(circulant)
      freeHeapAligned(u)
      return

  # u is already in time domain (toeplitzMatVecMulPreFFT did IFFT)
  # Zero upper half, degree is CDS/2 - 1
  for i in CDSdiv2 ..< CDS:
    u[i].setNeutral()

  # FFT to get proofs
  let proofsJac = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)
  let status3 = ec_fft_desc.ec_fft_nr(proofsJac.toOpenArray(CDS), u.toOpenArray(CDS))
  if status3 != FFT_Success:
    freeHeapAligned(proofsJac)
    freeHeapAligned(circulant)
    freeHeapAligned(u)
    return

  proofs.asUnchecked().batchAffine(proofsJac, proofs.len)

  freeHeapAligned(proofsJac)
  freeHeapAligned(circulant)
  freeHeapAligned(u)

# ############################################################
#
#    EIP-7594 - Cell KZG Proof Batch Verification
#
# ############################################################
# Universal verification equation from KDF22 (Kadianakis, Dietrichs, Feist):
# https://ethresear.ch/t/a-universal-verification-equation-for-data-availability-sampling/13240
#
# e(∑ₖ rᵏ πₖ, [sᴰ]₂) = e(∑ᵢ(∑ₖ∈rowᵢ rᵏ)Cᵢ - [∑ₖ rᵏ Iₖ(s)] + ∑ₖ rᵏ hₖᴰπₖ, [1]₂)
#
# Security: Randomizers prevent rogue key attacks (Bernstein 2012)
# https://cr.yp.to/badbatch/badbatch-20120919.pdf (Section 3.2)

func computeCommitmentToAggregatedInterpolationPoly*[Name: static Algebra, CosetSize: static int](
       commitment: var EC_ShortW_Aff[Fp[Name], G1],
       rPowers: ptr UncheckedArray[Fr[Name]],
       cellIndices: ptr UncheckedArray[uint64],
       cosetsEvals: ptr UncheckedArray[array[CosetSize, Fr[Name]]],
       numCells: int,
       omegaD: Fr[Name],  # D-th root of unity (precomputed)
       rootsOfUnity: ptr UncheckedArray[Fr[Name]],  # Bit-reversed, length = CELLS_PER_EXT_BLOB * D + 1
       rootsOfUnityLen: int,  # Length of rootsOfUnity array
       srs_monomial_g1: ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]]): void {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute RLI = [∑ₖ rᵏ Iₖ(s)]
  ## Follows c-kzg-4844:eip7594.c:592-748

  const D = CosetSize
  const CELLS_PER_EXT_BLOB = 128

  # Step 1: Aggregate cells from same column (scale by r^k)
  var aggregatedColumns = newSeq[array[D, Fr[Name]]](CELLS_PER_EXT_BLOB)
  for k in 0 ..< numCells:
    let colIdx = cellIndices[k].int
    if aggregatedColumns[colIdx].len == 0:
      for j in 0 ..< D: aggregatedColumns[colIdx][j].setZero()
    for j in 0 ..< D:
      var scaled: Fr[Name]
      scaled.prod(rPowers[k], cosetsEvals[k][j])
      aggregatedColumns[colIdx][j].sum(aggregatedColumns[colIdx][j], scaled)

  # Step 2: Compute sum of interpolation polynomials
  var sumInterpPolys = newSeq[Fr[Name]](D)
  for j in 0 ..< D: sumInterpPolys[j].setZero()

  for colIdx in 0 ..< CELLS_PER_EXT_BLOB:
    if aggregatedColumns[colIdx].len == 0: continue

    # Skip empty columns
    var isEmpty = true
    for j in 0 ..< D:
      if not bool(aggregatedColumns[colIdx][j].isZero()):
        isEmpty = false
        break
    if isEmpty: continue

    # Get coset shift h_k = ω^(reverseBits(colIdx, 7) * D)
    let colIdxRbl = reverseBits(uint32(colIdx), 7u32)
    let h_k = rootsOfUnity[(uint64(colIdxRbl) * uint64(D)) mod uint64(rootsOfUnityLen - 1)]

    # Use coset IFFT: coset evaluations → coefficients
    var columnEvals = newSeq[Fr[Name]](D)
    for j in 0 ..< D: columnEvals[j] = aggregatedColumns[colIdx][j]

    var columnInterpPoly = newSeq[Fr[Name]](D)
    let cosetDesc = FrFFT_Descriptor[Fr[Name]].new(order = D, generatorRootOfUnity = omegaD)
    discard cosetDesc.coset_ifft_rn(columnInterpPoly, columnEvals, h_k)

    for j in 0 ..< D:
      sumInterpPolys[j].sum(sumInterpPolys[j], columnInterpPoly[j])

  # Step 3: Commit via MSM
  var commitmentJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  commitmentJac.multiScalarMul_vartime(sumInterpPolys.asUnchecked(), srs_monomial_g1, D)
  commitment.affine(commitmentJac)

func kzg_coset_verify_batch*[Name: static Algebra, CosetSize: static int](
       commitments: ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]],
       numCommitments: int,
       commitmentIndices: ptr UncheckedArray[uint64],
       cellIndices: ptr UncheckedArray[uint64],
       cosetsEvals: ptr UncheckedArray[array[CosetSize, Fr[Name]]],
       proofs: ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]],
       numCells: int,
       linearIndepRandNumbers: ptr UncheckedArray[Fr[Name]],  # Precomputed r^0, r^1, ..., r^{numCells-1}
       omegaD: Fr[Name],  # D-th root of unity (precomputed)
       rootsOfUnity: ptr UncheckedArray[Fr[Name]],  # Bit-reversed, length = CELLS_PER_EXT_BLOB * D + 1
       rootsOfUnityLen: int,  # Length of rootsOfUnity array
       srs_monomial_g1: ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]],
       srs_monomial_g2: ptr UncheckedArray[EC_ShortW_Aff[Fp2[Name], G2]]): bool {.tags:[Alloca, HeapAlloc, Vartime, WriteIOEffect].} =
  ## Verify batch using universal equation: e(LL, LR) = e(RL, [1]₂)
  ## Mirrors kzg_verify_batch API - accepts precomputed linearIndepRandNumbers

  const D = CosetSize
  if numCells == 0: return true

  # LL = ∑ₖ rᵏ πₖ
  let coefs = allocHeapArrayAligned(Fr[Name].getBigInt(), numCells, alignment = 64)
  coefs.batchFromField(linearIndepRandNumbers, numCells)
  var llJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  llJac.multiScalarMul_vartime(coefs, cast[ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]]](proofs), numCells)
  freeHeapAligned(coefs)

  # LR = [sᴰ]₂
  let lr = srs_monomial_g2[D]

  # RLC = ∑ᵢ weights[i] Cᵢ
  var commitmentWeights = newSeq[Fr[Name]](numCommitments)
  for i in 0 ..< numCommitments: commitmentWeights[i].setZero()
  for k in 0 ..< numCells:
    commitmentWeights[commitmentIndices[k].int].sum(commitmentWeights[commitmentIndices[k].int], linearIndepRandNumbers[k])

  let commitCoefs = allocHeapArrayAligned(Fr[Name].getBigInt(), numCommitments, alignment = 64)
  commitCoefs.batchFromField(commitmentWeights.asUnchecked(), numCommitments)
  var rlcJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  rlcJac.multiScalarMul_vartime(commitCoefs, cast[ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]]](commitments), numCommitments)
  freeHeapAligned(commitCoefs)

  # RLI = [∑ₖ rᵏ Iₖ(s)]
  var rliAff {.noInit.}: EC_ShortW_Aff[Fp[Name], G1]
  computeCommitmentToAggregatedInterpolationPoly[Name, CosetSize](
    rliAff, linearIndepRandNumbers, cellIndices, cosetsEvals, numCells, omegaD, rootsOfUnity, rootsOfUnityLen, srs_monomial_g1)
  var rliJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  rliJac.fromAffine(rliAff)

  # RLP = ∑ₖ (rᵏ * hₖᴰ) πₖ
  var weightedRPowers = newSeq[Fr[Name]](numCells)
  for k in 0 ..< numCells:
    let cellIdxRbl = reverseBits(uint32(cellIndices[k]), 7u32)
    let h_k_pow = rootsOfUnity[(uint64(cellIdxRbl) * uint64(D)) mod uint64(rootsOfUnityLen - 1)]
    weightedRPowers[k].prod(linearIndepRandNumbers[k], h_k_pow)

  let weightedCoefs = allocHeapArrayAligned(Fr[Name].getBigInt(), numCells, alignment = 64)
  weightedCoefs.batchFromField(weightedRPowers.asUnchecked(), numCells)
  var rlpJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  rlpJac.multiScalarMul_vartime(weightedCoefs, cast[ptr UncheckedArray[EC_ShortW_Aff[Fp[Name], G1]]](proofs), numCells)
  freeHeapAligned(weightedCoefs)

  # RL = RLC - RLI + RLP
  var rlJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  rlJac.sum_vartime(rlcJac, rlpJac)
  rlJac.diff_vartime(rlJac, rliJac)

  # Pairing: e(LL, LR) = e(RL, [1]₂)
  var llAff, rlAff {.noInit.}: EC_ShortW_Aff[Fp[Name], G1]
  llAff.affine(llJac)
  rlAff.affine(rlJac)

  # Debug output for comparison with Python (use debugEcho to avoid sideEffect)
  if numCells > 1:
    var llBytes, rlcBytes, rliBytes, rlpBytes, rlBytes: array[48, byte]
    var lrBytes: array[96, byte]
    var rlcAff, rlpAff {.noInit.}: EC_ShortW_Aff[Fp[Name], G1]
    rlcAff.affine(rlcJac)
    rlpAff.affine(rlpJac)
    discard llBytes.serialize_g1_compressed(llAff)
    discard rlcBytes.serialize_g1_compressed(rlcAff)
    discard rliBytes.serialize_g1_compressed(rliAff)
    discard rlpBytes.serialize_g1_compressed(rlpAff)
    discard rlBytes.serialize_g1_compressed(rlAff)
    discard lrBytes.serialize_g2_compressed(lr)

    debugEcho "\n  [DEBUG from kzg_coset_verify_batch]"
    debugEcho "    LL  = ", toHex(llBytes.toOpenArray(0, llBytes.high))
    debugEcho "    RLC = ", toHex(rlcBytes.toOpenArray(0, rlcBytes.high))
    debugEcho "    RLI = ", toHex(rliBytes.toOpenArray(0, rliBytes.high))
    debugEcho "    RLP = ", toHex(rlpBytes.toOpenArray(0, rlpBytes.high))
    debugEcho "    RL  = ", toHex(rlBytes.toOpenArray(0, rlBytes.high))
    debugEcho "    LR (G2) = ", toHex(lrBytes.toOpenArray(0, lrBytes.high))

  type F2 = Fp2[Name]
  var negG2 {.noInit.}: EC_ShortW_Aff[F2, G2]
  negG2.neg(Name.getGenerator("G2"))

  var gt {.noInit.}: Name.getGT()
  gt.pairing([llAff, rlAff], [lr, negG2])

  result = gt.isOne().bool()
