# Constantine
# Copyright (c) 2018-2019    Status Research & Development GmbH
# Copyright (c) 2020-Present Mamy André-Ratsimbazafy
# Licensed and distributed under either of
#   * MIT license (license terms in the root directory or at http://opensource.org/licenses/MIT).
#   * Apache v2 license (license terms in the root directory or at http://www.apache.org/licenses/LICENSE-2.0).
# at your option. This file may not be copied, modified, or distributed except according to those terms.

# Compile and run with:
#   nim c -r -d:release --hints:off --warnings:off --outdir:build/tmp --nimcache:nimcache/tmp tests/commitments/t_kzg_multiproofs.nim

import
  constantine/named/[algebras, zoo_generators],
  constantine/math/[ec_shortweierstrass, arithmetic, extension_fields],
  constantine/math/elliptic/ec_multi_scalar_mul,
  constantine/math/pairings/pairings_generic,
  constantine/math/polynomials/[polynomials, fft],
  constantine/math/matrix/toeplitz,
  constantine/platforms/[abstractions, allocs, bithacks, views]


# ############################################################
#
#           KZG coset (Multi-Proof)
#
# ############################################################
#
# Nomenclature
# ~~~~~~~~~~~~
#
# - N: Polynomial size
# - L: coset size
# - CDS (Circulant Domain Size): Extended domain size = 2 * N/L

func kzg_coset_prove_naive*[N, L: static int, Name: static Algebra](
       proof: var EC_ShortW_Aff[Fp[Name], G1],
       ys: var array[L, Fr[Name]],
       poly: PolynomialCoef[N, Fr[Name]],
       x: Fr[Name],
       lthRoot: Fr[Name],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute a KZG multi-evaluation proof for a polynomial at L points on a coset.
  ##
  ## This is the NON-OPTIMIZED "schoolbook" O(n²) algorithm using polynomial long division.
  ## For production use with many cells, see `kzg_coset_prove` (FK20 O(n log n)).
  ##
  ## Background on Cosets
  ## ~~~~~~~~~~~~~~~~~~~~
  ##
  ## A coset is a shifted subgroup. In KZG data availability sampling:
  ##   - We have a subgroup G of order L, generated by ω (L-th root of unity)
  ##   - The coset for cell i is: x_i * G = {x_i, x_i·ω, x_i·ω², ..., x_i·ω^(L-1)}
  ##   - where x_i is the coset representative (different for each cell)
  ##
  ## The proof allows verifying all L evaluations simultaneously with a single G1 element.
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## Algorithm
  ## ~~~~~~~~~
  ##
  ## Given polynomial p(X) and coset points {x·ω⁰, x·ω¹, ..., x·ω^(L-1)}:
  ##
  ## 1. Compute evaluations: y_j = p(x·ω^j) for j in 0..L-1
  ##
  ## 2. Build vanishing polynomial:
  ##      Z(X) = X^L - x^L = (X - x·ω⁰)(X - x·ω¹)...(X - x·ω^(L-1))
  ##    In coefficient form: [-x^L, 0, 0, ..., 0, 1] (degree L)
  ##
  ## 3. Compute quotient q(X) = p(X) / Z(X) via polynomial long division
  ##    This works because Z(X) divides p(X) - I(X) where I is the interpolation polynomial.
  ##    Since deg(I) < deg(Z), we have p(X) / Z(X) = q(X) exactly.
  ##
  ## 4. Compute proof = [q(τ)]₁ = Σ q_i · [τ^i]₁ via linear combination
  ##
  ## Verification Equation
  ## ~~~~~~~~~~~~~~~~~~~~~~
  ##
  ## The verifier checks:
  ##    e(commitment - v(τ), [1]₂) = e(proof, τ^L - x^L)
  ##
  ## where v(X) is the degree-(L-1) polynomial interpolating p on the coset.
  ##
  ## This works because:
  ##    p(X) - v(X) = q(X) · (X^L - x^L)
  ##    Evaluating at τ: p(τ) - v(τ) = q(τ) · (τ^L - x^L)
  ##    Rearranging: q(τ) = (p(τ) - v(τ)) / (τ^L - x^L)
  ##
  ## Parameters
  ## ~~~~~~~~~~
  ##
  ## - proof: Output KZG proof (single G1 element)
  ## - ys: Output array of L evaluations p(x·ω^j)
  ## - poly: Input polynomial in coefficient form (degree N-1)
  ## - x: Coset representative (the "shift" or "offset")
  ## - lthRoot: The primitive L-th root of unity ω (such that ω^L = 1, ω^k ≠ 1 for k < L)
  ## - powers_of_tau: SRS [G, τG, τ²G, ..., τ^(N-1)G] in affine form
  ##
  ## References
  ## ~~~~~~~~~~
  ##
  ## - ethereum/research: compute_proof_multi() in kzg_data_availability/kzg_proofs.py
  ## - ethereum/consensus-specs: compute_kzg_proof_multi_impl() in specs/fulu/polynomial-commitments-sampling.md

  static:
    doAssert N > L, "Polynomial degree must be > coset size"
    doAssert L.isPowerOf2_vartime(), "Coset size L must be a power of 2"

  let xPowL = x ~^ uint32(L)

  var divisor {.noInit.}: PolynomialCoef[L + 1, Fr[Name]]
  divisor.coefs[0].neg(xPowL)
  for i in 1 ..< L:
    divisor.coefs[i].setZero()
  divisor.coefs[L].setOne()

  var quotient {.noInit.}: PolynomialCoef[N, Fr[Name]]
  polyDiv(quotient, poly, divisor)

  var proofJac {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
  proofJac.multiScalarMul_vartime(quotient.coefs, powers_of_tau.coefs)
  proof.affine(proofJac)

  var omegaPow {.noInit.}: Fr[Name]
  omegaPow.setOne()

  for j in 0 ..< L:
    var z {.noInit.}: Fr[Name]
    z.prod(x, omegaPow)
    evalPolyAt(ys[j], poly, z)
    omegaPow *= lthRoot

func kzg_coset_verify*[L: static int, Name: static Algebra](
       commitment: EC_ShortW_Aff[Fp[Name], G1],
       proof: EC_ShortW_Aff[Fp[Name], G1],
       x: Fr[Name],
       ys: array[L, Fr[Name]],
       powers_of_tau: PolynomialCoef[L, EC_ShortW_Aff[Fp[Name], G1]],
       tauG2_powers: array[L+1, EC_ShortW_Aff[Fp2[Name], G2]],
       lthRoot: Fr[Name],
       N: static int): bool {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Verify a KZG cell (multi-proof) for L evaluation points.
  ##
  ## This version accepts the full G2 powers [1]₂, [τ]₂, [τ²]₂, ..., [τᴸ]₂
  ## needed for the τᴸ - xᴸ computation.
  ##
  ## Given:
  ##   - commitment C = [p(τ)]G₁
  ##   - proof π = [v(τ)]G₁ where v(X) is degree-(L-1) polynomial interpolating p on coset
  ##   - x: coset representative (e.g., ωⁱ for i-th cell)
  ##   - ys: [p(x·ω⁰), p(x·ω¹), ..., p(x·ωᴸ⁻¹)] in standard order
  ##
  ## Verification equation (FK20 paper, Section 4):
  ##   e(commitment - v(τ), 1) = e(proof, τᴸ - xᴸ)
  var
    interpolation {.noInit.}: PolynomialCoef[L, Fr[Name]]
    vTau {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    commitMinusV {.noInit.}: EC_ShortW_Jac[Fp[Name], G1]
    xL_G2 {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    tauMinusX_G2 {.noInit.}: EC_ShortW_Jac[Fp2[Name], G2]
    negG2 {.noInit.}: EC_ShortW_Aff[Fp2[Name], G2]

  # Step 1: Interpolate ys at roots of unity using coset IFFT
  #         The shift is needed to unshift from coset points back to coefficients
  let cosetDesc = CosetFFT_Descriptor[Fr[Name]].new(order = L, generatorRootOfUnity = lthRoot, shift = x)
  let status = coset_ifft_rn(cosetDesc, interpolation.coefs, ys)
  if status != FFT_Success:
    return false

  let xPowL = x ~^ uint32(L)

  # Step 2: Compute v(τ) = Σ interpolation[i] * τⁱ
  vTau.multiScalarMul_vartime(interpolation.coefs, powers_of_tau.coefs)

  # Step 3: Compute commitment - v(τ)
  commitMinusV.fromAffine(commitment)
  commitMinusV -= vTau

  # Step 4: Compute τᴸ - xᴸ in G2
  tauMinusX_G2.fromAffine(tauG2_powers[L])
  xL_G2.setGenerator()
  xL_G2.scalarMul_vartime(xPowL)
  tauMinusX_G2 -= xL_G2

  # Step 5: Verify pairing e(commit - v, 1) = e(proof, τᴸ - xᴸ)
  negG2.neg(Name.getGenerator("G2"))

  return pairing_check(commitMinusV, negG2, proof, tauMinusX_G2)

# ############################################################
#
#           FK20 - Fast amortized KZG proofs
#
# ############################################################
#
# Algorithm from FK20 paper (Feist, Khovratovich):
#  https://raw.githubusercontent.com/khovratovich/Kate/master/Kate_amortized.pdf
#
# Long eprint:
# https://eprint.iacr.org/2023/033
#
# Computes multiple KZG proofs simultaneously in O(n log n) time
# instead of O(n²) for individual proofs.
#
# Nomenclature
# ~~~~~~~~~~~~
#
# - N: Polynomial size
# - L: coset size
# - CDS (Circulant Domain Size): Extended domain size = 2 * N/L
#
# For EIP-7594 PeerDAS:
#   N = 4096 (FIELD_ELEMENTS_PER_BLOB),
#   L = 64 (FIELD_ELEMENTS_PER_CELL)
#   N/L = CELLS_PER_BLOB, 64 blobs with each 64 cells
#   CDS = 128

func getTauExtFft[N, CDS: static int, Name: static Algebra](
       tauExtFft: var array[CDS, EC_ShortW_Jac[Fp[Name], G1]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       domainRoot: Fr[Name],
       offset: int = 0) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Convert powers_of_tau (SRS coefficients) to tauExtFft (FFT of kernel sequence).
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## @param tauExtFft: Output array for FFT of kernel sequence (length CDS)
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ...] (affine, length N)
  ## @param domainRoot: Primitive CDS-th root of unity for FFT
  ## @param offset: Offset for kernel extraction (default 0, range 0..L-1)

  const CDSdiv2 = CDS shr 1
  const L = N div CDSdiv2

  static:
    doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"

  let ecFftDesc = ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]].new(order = CDS, domainRoot)

  let kernelSeq = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)

  # Extract kernel with stride L and given offset (convert affine to projective for FFT)
  let start = if N >= L + 1 + offset: N - L - 1 - offset else: 0
  var j = start
  for i in 0 ..< CDSdiv2 - 1:
    kernelSeq[i].fromAffine(powers_of_tau.coefs[j])
    j -= L
  kernelSeq[CDSdiv2 - 1].setNeutral()
  for j in CDSdiv2 ..< CDS:
    kernelSeq[j].setNeutral()

  # FFT the kernel to get tauExtFft
  let status = ec_fft_nr(ecFftDesc, tauExtFft, kernelSeq.toOpenArray(CDS))
  if status != FFT_Success:
    freeHeapAligned(kernelSeq)
    return

  freeHeapAligned(kernelSeq)

func getTauExtFftArray*[N, L, CDS: static int, Name: static Algebra](
       tauExtFftArray: var array[L, array[CDS, EC_ShortW_Jac[Fp[Name], G1]]],
       powers_of_tau: PolynomialCoef[N, EC_ShortW_Aff[Fp[Name], G1]],
       domainRoot: Fr[Name]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute tauExtFft for all L offsets.
  ##
  ## This is the complete FK20 preprocessing phase. It computes the FFT of
  ## the kernel sequence for each offset in 0..L-1.
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096
  ##   L = FIELD_ELEMENTS_PER_CELL = 64
  ##   CDS = 2 * CELLS_PER_BLOB = 128
  ##
  ## This corresponds to:
  ##   - ethereum/research: fk20_multi.py lines 46-49: xext_fft = [] for i in range(l)
  ##   - ethereum/c-kzg-4844: s->x_ext_fft_columns (precomputed during setup)
  ##
  ## The result can be cached and reused for multiple polynomials.
  ##
  ## @param tauExtFftArray: Output array[L][CDS] for FFT of kernel sequences
  ## @param powers_of_tau: SRS in coefficient form [G, τG, τ²G, ..., τⁿ⁻¹G] (affine, length N)
  ## @param domainRoot: Primitive CDS-th root of unity for FFT
  ##
  ## @see getTauExtFft for computing a single offset
  static: doAssert CDS * L == 2 * N

  for offset in 0 ..< L:
    getTauExtFft(tauExtFftArray[offset], powers_of_tau, domainRoot, offset)

func kzg_coset_prove*[N, L, CDS: static int, Name: static Algebra](
       tauExtFftArray: array[L, array[CDS, EC_ShortW_Jac[Fp[Name], G1]]],
       circulantDomain: PolyEvalRootsDomain[CDS, Fr[Name]],
       proofs: var array[CDS, EC_ShortW_Aff[Fp[Name], G1]],
       poly: PolynomialCoef[N, Fr[Name]]) {.tags:[Alloca, HeapAlloc, Vartime].} =
  ## Compute KZG multi-proofs for EIP-7594 cell proofs using FK20 algorithm.
  ##
  ## This implements the FK20 amortized KZG proofs from c-kzg-4844.
  ## Uses Toeplitz matrix-vector multiplication with FFT for O(n log n) performance.
  ##
  ## For EIP-7594 PeerDAS:
  ##   N = FIELD_ELEMENTS_PER_BLOB = 4096 (polynomial size)
  ##   L = FIELD_ELEMENTS_PER_CELL = 64 (stride/loop count, evaluations per cell)
  ##   CDS = 2 * CELLS_PER_BLOB = 128 (output proof count)
  ##
  ## Algorithm (Phase 1 + Phase 2 from FK20):
  ##   For each stride offset in [0, L):
  ##     1. Extract toeplitz coefficients from poly
  ##     2. toeplitzMatVecMul: FFT coeffs + FFT kernel + pointwise multiply + IFFT
  ##     3. Accumulate result
  ##   Zero upper half
  ##   FFT → proofs
  ##
  ## Verification:
  ##   - If L == 1 (single evaluation per coset): Use regular `kzg_verify`
  ##   - If L > 1 (multiple evaluations per coset): Use `kzg_coset_verify`
  ##
  ## @param tauExtFft: Precomputed FFT of kernel sequence (length CDS)
  ## @param circulantDomain: Evaluation domain (roots of unity, length CDS)
  ## @param proofs: Output array for CDS proofs (affine form)
  ## @param poly: Polynomial to prove (length N, coefficient/monomial form)

  const CDSdiv2 = CDS shr 1
  const N = L * CDSdiv2

  static:
    doAssert CDS.isPowerOf2_vartime(), "CDS must be a power of two"

  let frFftDesc = FrFFT_Descriptor[Fr[Name]].new(order = CDS, circulantDomain.rootsOfUnity[1])
  let ecFftDesc = ECFFT_Descriptor[EC_ShortW_Jac[Fp[Name], G1]].new(order = CDS, circulantDomain.rootsOfUnity[1])

  let u = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)
  for i in 0 ..< CDS:
    u[i].setNeutral()

  let circulant = allocHeapArrayAligned(Fr[Name], CDS, alignment = 64)

  for offset in 0 ..< L:
    makeCirculantMatrix(circulant.toOpenArray(CDS), poly.coefs, offset, L)

    # Use toeplitzMatVecMulPreFFT with accumulate=true
    # This does: FFT(toeplitzCoeffs) ⊙ kernelFft, then IFFT → result
    # Results are accumulated in time domain
    let status = toeplitzMatVecMulPreFFT(
      u.toOpenArray(CDS),
      circulant.toOpenArray(CDS),
      tauExtFftArray[offset],
      frFftDesc,
      ecFftDesc,
      accumulate = (offset > 0)
    )
    if status != FFT_Success:
      freeHeapAligned(circulant)
      freeHeapAligned(u)
      return

  # u is already in time domain (toeplitzMatVecMulSameSize did IFFT)
  # Zero upper half, degree is CDS/2 - 1
  for i in CDSdiv2 ..< CDS:
    u[i].setNeutral()

  # FFT to get proofs
  let proofsJac = allocHeapArrayAligned(EC_ShortW_Jac[Fp[Name], G1], CDS, alignment = 64)
  let status3 = ecFftDesc.ec_fft_nr(proofsJac.toOpenArray(CDS), u.toOpenArray(CDS))
  if status3 != FFT_Success:
    freeHeapAligned(proofsJac)
    freeHeapAligned(circulant)
    freeHeapAligned(u)
    return

  proofs.asUnchecked().batchAffine(proofsJac, proofs.len)

  freeHeapAligned(proofsJac)
  freeHeapAligned(circulant)
  freeHeapAligned(u)
